### ISSUE TITLE
UrbanAirship 8.3.4 support

### ISSUE THREAD

**Issue by ekazaev** [mparticle-integrations/mparticle-apple-integration-urbanairship#5]
Could you please update the library to support latest version of Urbanairship as the fixed there one crash that is important for us.

Thank you.

**Comment by samdozor** [comment]
Hi @ekazaev the kit podspec specifies `'UrbanAirship-iOS-SDK', '~> 8.3.0'`, so it should pull in 8.3.4 automatically. Please make sure you run a `pod update` in your local environment (not `pod install`)

**Comment by ekazaev** [comment]
Hi, thank you for your reply,

I actually did a typo. Not 8.3.4 but 8.4.3. So it can not be updated until you update your podspec. Sorry for the confusion.
Here is the ticket number with a fix.
https://support.urbanairship.com/hc/en-us/requests/38476?flash_digest=18da11217fd9010d8cdd5ea41970ad9f056c3968 <https://support.urbanairship.com/hc/en-us/requests/38476?flash_digest=18da11217fd9010d8cdd5ea41970ad9f056c3968>
 
Regards,
Eugene.

**Comment by samdozor** [comment]
Hi @ekazaev - we've just released 6.14.5 which points to the latest UA SDK.
