### ISSUE TITLE
Please update podspec to support latest UA SDK

### ISSUE THREAD

**Issue by ekazaev** [mparticle-integrations/mparticle-apple-integration-urbanairship#7]
Please update podspec to support latest UA SDK.
We are experiencing number of crashes related to the issue described here https://support.urbanairship.com/hc/en-us/requests/39697. According to the UA reply it was fixed in UrbanAirship SDK 8.5.3.

**Comment by samdozor** [comment]
@ekazaev this will be updated in this weeks release - thanks!
